# Generated by Django 5.0.1 on 2025-12-21 23:52

import django.core.validators
import django.db.models.deletion
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=videos.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('fps', models.FloatField(blank=True, help_text='Frames per second', null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RhythmGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bpm', models.FloatField(help_text='Beats per minute', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('time_signature_numerator', models.IntegerField(default=4, help_text='Top number of time signature (e.g., 4 in 4/4)', validators=[django.core.validators.MinValueValidator(1)])),
                ('time_signature_denominator', models.IntegerField(default=4, help_text='Bottom number of time signature (e.g., 4 in 4/4)', validators=[django.core.validators.MinValueValidator(1)])),
                ('offset_start', models.FloatField(default=0.0, help_text='Timestamp in seconds where beat 1 occurs', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rhythm_grid', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar_start', models.IntegerField(help_text='Starting bar index (0-based)', validators=[django.core.validators.MinValueValidator(0)])),
                ('bar_end', models.IntegerField(help_text='Ending bar index (inclusive)', validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for classification')),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='videos.video')),
            ],
            options={
                'ordering': ['bar_start'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['owner', '-created_at'], name='videos_vide_owner_i_6a9499_idx'),
        ),
        migrations.AddIndex(
            model_name='rhythmgrid',
            index=models.Index(fields=['video'], name='videos_rhyt_video_i_f52cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='fragment',
            index=models.Index(fields=['video', 'bar_start'], name='videos_frag_video_i_a0b5c1_idx'),
        ),
    ]
