# Generated by Django 5.0.1 on 2025-12-22 06:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.FloatField(help_text='Time in seconds when this beat occurs', validators=[django.core.validators.MinValueValidator(0)])),
                ('beat_number', models.IntegerField(help_text='Sequential beat number (1, 2, 3, ...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('rhythm_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_markers', to='videos.rhythmgrid')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['rhythm_grid', 'timestamp'], name='videos_beat_rhythm__2e4239_idx')],
                'unique_together': {('rhythm_grid', 'beat_number')},
            },
        ),
    ]
