# Generated by Django 5.0.1 on 2026-01-05 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_beatmarker'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('counter', 'Counter'), ('alert', 'Alert')], max_length=20)),
                ('start_time', models.FloatField(default=0.0, help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('x', models.FloatField(default=50.0, help_text='X position as percentage')),
                ('y', models.FloatField(default=50.0, help_text='Y position as percentage')),
                ('visible', models.BooleanField(default=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Element-specific properties (content, fontSize, fontColor, etc.)')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='videos.video')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.DeleteModel(
            name='BeatMarker',
        ),
        migrations.AddIndex(
            model_name='videoelement',
            index=models.Index(fields=['video', 'element_type'], name='videos_vide_video_i_a220b8_idx'),
        ),
    ]
