# Generated by Django 5.0.1 on 2026-03-03 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoelement_delete_beatmarker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for anonymous users', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['session_key', '-created_at'], name='videos_vide_session_51e881_idx'),
        ),
    ]
