# Generated by Django 5.0.1 on 2026-03-03 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0004_video_session_key_alter_video_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_brl', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_product_id', models.CharField(blank=True, max_length=128)),
                ('stripe_price_id', models.CharField(blank=True, max_length=128)),
                ('storage_limit_gb', models.IntegerField(help_text='Max storage in GB')),
                ('export_minutes_per_month', models.IntegerField(help_text='Monthly export minutes included')),
                ('max_resolution', models.CharField(default='1080p', help_text='Max export resolution (1080p, 4k)', max_length=10)),
                ('export_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('auto_delete_days', models.IntegerField(default=7, help_text='Days before inactive projects are auto-deleted')),
                ('allows_4k', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'price_brl'],
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Remaining subscription minutes for current billing cycle', max_digits=10)),
                ('purchased_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Purchased credit minutes (never expire)', max_digits=10)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Credit balances',
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Credits Reserved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('resolution', models.CharField(choices=[('1080p', '1080p'), ('4k', '4K')], default='1080p', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('estimated_duration_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Estimated export duration in minutes', max_digits=10)),
                ('credits_consumed', models.DecimalField(decimal_places=2, default=0, help_text='Actual credits debited (after 4K multiplier)', max_digits=10)),
                ('credit_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='1.0 for 1080p, 2.0 for 4K', max_digits=4)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('output_file_url', models.URLField(blank=True)),
                ('output_file_size', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit (export)'), ('reset', 'Monthly Reset'), ('purchase', 'Credit Purchase'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment')], max_length=16)),
                ('minutes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_minutes_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchased_minutes_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('export_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='billing.exportjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bytes_used', models.BigIntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Storage usage',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired')], default='incomplete', max_length=24)),
                ('stripe_subscription_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=128)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['user', '-created_at'], name='billing_exp_user_id_f085a8_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['status'], name='billing_exp_status_ad46b6_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', '-created_at'], name='billing_cre_user_id_b1ca8c_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_type'], name='billing_cre_transac_d45d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_customer_id'], name='billing_sub_stripe__97887e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='billing_sub_status_948046_idx'),
        ),
    ]
