# Generated by Django 5.0.1 on 2026-03-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='export_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='output_file_url',
            field=models.TextField(blank=True),
        ),
    ]
