# Generated by Django 5.0.1 on 2026-03-03 03:10

import classroom.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0004_video_session_key_alter_video_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dance_style', models.CharField(blank=True, help_text='Estilo de dança (ex: forró, samba, zouk, salsa)', max_length=50)),
                ('invite_code', models.CharField(db_index=True, default=classroom.models.generate_invite_code, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_students', models.IntegerField(default=50)),
                ('cover_color', models.CharField(default='#6366F1', help_text='Hex color for classroom card', max_length=7)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Instruções detalhadas para o aluno')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('closed', 'Encerrado')], default='draft', max_length=12)),
                ('focus_bar_start', models.IntegerField(blank=True, help_text='Compasso inicial para focar', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('focus_bar_end', models.IntegerField(blank=True, help_text='Compasso final para focar', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_bpm', models.FloatField(blank=True, help_text='BPM sugerido para o exercício', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('reference_video', models.ForeignKey(blank=True, help_text='Vídeo de referência do professor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_as_reference', to='videos.video')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classroom.classroom')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='videos.video')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classroom.classroom')),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('student', 'Aluno'), ('assistant', 'Monitor')], default='student', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='classroom.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_comment', models.TextField(help_text='Comentário geral sobre a performance')),
                ('grade', models.IntegerField(blank=True, choices=[(1, 'Precisa Melhorar Muito'), (2, 'Precisa Melhorar'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.JSONField(blank=True, default=list, help_text='Lista de pontos fortes')),
                ('improvements', models.JSONField(blank=True, default=list, help_text='Lista de pontos a melhorar')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar_number', models.IntegerField(help_text='Número do compasso (0-based)', validators=[django.core.validators.MinValueValidator(0)])),
                ('beat_number', models.IntegerField(default=1, help_text='Número do tempo dentro do compasso (1-based)', validators=[django.core.validators.MinValueValidator(1)])),
                ('time_position', models.FloatField(blank=True, help_text='Posição em segundos (fallback se não houver BPM)', null=True)),
                ('annotation_type', models.CharField(choices=[('correction', 'Correção'), ('praise', 'Elogio'), ('tip', 'Dica'), ('reference', 'Referência')], default='correction', max_length=12)),
                ('comment', models.TextField()),
                ('reference_bar', models.IntegerField(blank=True, help_text='Compasso no vídeo de referência do professor', null=True)),
                ('reference_time', models.FloatField(blank=True, help_text='Tempo em segundos no vídeo de referência', null=True)),
                ('color', models.CharField(default='#EF4444', help_text='Cor do marcador (vermelho=correção, verde=elogio, azul=dica)', max_length=7)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='classroom.feedback')),
            ],
            options={
                'ordering': ['bar_number', 'beat_number'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Enviado'), ('in_review', 'Em Revisão'), ('approved', 'Aprovado'), ('needs_work', 'Precisa Melhorar'), ('rejected', 'Rejeitado')], default='submitted', max_length=16)),
                ('student_notes', models.TextField(blank=True, help_text='Notas do aluno sobre a submissão')),
                ('attempt_number', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classroom.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='videos.video')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='classroom.submission'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('teacher', 'Professor'), ('student', 'Aluno')], default='student', max_length=10)),
                ('bio', models.TextField(blank=True, help_text='Bio do professor')),
                ('specialties', models.JSONField(blank=True, default=list, help_text="Lista de especialidades (ex: ['forró', 'samba', 'zouk'])")),
                ('avatar_url', models.URLField(blank=True)),
                ('skill_level', models.CharField(blank=True, choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['teacher', '-created_at'], name='classroom_c_teacher_c2101f_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['invite_code'], name='classroom_c_invite__8ee66c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['classroom', 'status'], name='classroom_a_classro_67a44a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroommember',
            unique_together={('classroom', 'user')},
        ),
        migrations.AddIndex(
            model_name='feedbackannotation',
            index=models.Index(fields=['feedback', 'bar_number'], name='classroom_f_feedbac_a6f36e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student'], name='classroom_s_assignm_6732e0_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='classroom_s_status_fc9da7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='classroom_u_role_10ce26_idx'),
        ),
    ]
